name: vimms-gym
channels:
- conda-forge
dependencies:
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - scikit-learn
  - loguru
  - jupyterlab
  - ipywidgets
  - pytorch
  - gym
  - stable-baselines3
  - pip
  - pip:
    - vimms
    - tensorboard