name: vimms-gym
channels:
  - defaults
dependencies:
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - scikit-learn
  - loguru
  - jupyterlab
  - ipywidgets
  - pytorch
  - streamlit
  - pip
  - pip:
    - vimms
    - stable-baselines3
    - gym
    - tensorboard
    - optuna
    - plotly
    - kaleido
    - cloudpickle==2.1.0
    - git+https://github.com/Stable-Baselines-Team/stable-baselines3-contrib.git