name: vimms-gym
channels:
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scipy
  - matplotlib
  - seaborn
  - scikit-learn
  - loguru
  - jupyterlab
  - ipywidgets
  - pytorch
  - streamlit
  - pip
  - pip:
    - vimms
    - gym
    - tensorboard
    - optuna
    - plotly
    - wandb
    - git+https://github.com/Stable-Baselines-Team/stable-baselines3-contrib@feat/gymnasium-support