name: vimms-gym
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - pandas
  - scipy
  - matplotlib
  - plotly
  - seaborn
  - scikit-learn
  - loguru
  - jupyterlab
  - ipywidgets
  - pytorch
  - gym
  - streamlit
  - pip
  - pip:
    - vimms
    - stable-baselines3
    - tensorboard
    - streamlit_plotly_events
    - streamlit_aggrid